// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALFyclhPtbVZj9yP2hF3XOhMF8ABpUtVY',
    appId: '1:289245330566:web:78a01e710ed97c8ae2e507',
    messagingSenderId: '289245330566',
    projectId: 'binpack-residents-and-driver',
    authDomain: 'binpack-residents-and-driver.firebaseapp.com',
    databaseURL: 'https://binpack-residents-and-driver-default-rtdb.firebaseio.com',
    storageBucket: 'binpack-residents-and-driver.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCc940H-zb39H5BsqAIZBtLQcd7soOmfBQ',
    appId: '1:289245330566:android:66253b5566daa802e2e507',
    messagingSenderId: '289245330566',
    projectId: 'binpack-residents-and-driver',
    databaseURL: 'https://binpack-residents-and-driver-default-rtdb.firebaseio.com',
    storageBucket: 'binpack-residents-and-driver.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsnzuYinOFJ06PR3NsY9RUR1byH6DUVag',
    appId: '1:289245330566:ios:6d1e5ec1f4a18a16e2e507',
    messagingSenderId: '289245330566',
    projectId: 'binpack-residents-and-driver',
    databaseURL: 'https://binpack-residents-and-driver-default-rtdb.firebaseio.com',
    storageBucket: 'binpack-residents-and-driver.appspot.com',
    iosClientId: '289245330566-hdeg28s46d9rhrlcl7vutk7h0ucioafs.apps.googleusercontent.com',
    iosBundleId: 'com.example.binpackr',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsnzuYinOFJ06PR3NsY9RUR1byH6DUVag',
    appId: '1:289245330566:ios:6d1e5ec1f4a18a16e2e507',
    messagingSenderId: '289245330566',
    projectId: 'binpack-residents-and-driver',
    databaseURL: 'https://binpack-residents-and-driver-default-rtdb.firebaseio.com',
    storageBucket: 'binpack-residents-and-driver.appspot.com',
    iosClientId: '289245330566-hdeg28s46d9rhrlcl7vutk7h0ucioafs.apps.googleusercontent.com',
    iosBundleId: 'com.example.binpackr',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyALFyclhPtbVZj9yP2hF3XOhMF8ABpUtVY',
    appId: '1:289245330566:web:ec151cdb4c46bb40e2e507',
    messagingSenderId: '289245330566',
    projectId: 'binpack-residents-and-driver',
    authDomain: 'binpack-residents-and-driver.firebaseapp.com',
    databaseURL: 'https://binpack-residents-and-driver-default-rtdb.firebaseio.com',
    storageBucket: 'binpack-residents-and-driver.appspot.com',
  );

}

// import 'package:flutter_dotenv/flutter_dotenv.dart';
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         return windows;
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static FirebaseOptions get web => FirebaseOptions(
//     apiKey: dotenv.env['FIREBASE_API_KEY']!,
//     appId: dotenv.env['FIREBASE_APP_ID_WEB']!,
//     messagingSenderId: dotenv.env['FIREBASE_MESSAGING_SENDER_ID']!,
//     projectId: dotenv.env['FIREBASE_PROJECT_ID']!,
//     authDomain: dotenv.env['FIREBASE_AUTH_DOMAIN']!,
//     databaseURL: dotenv.env['FIREBASE_DATABASE_URL']!,
//     storageBucket: dotenv.env['FIREBASE_STORAGE_BUCKET']!,
//   );

//   static FirebaseOptions get android => FirebaseOptions(
//     apiKey: dotenv.env['FIREBASE_API_KEY']!,
//     appId: dotenv.env['FIREBASE_APP_ID_ANDROID']!,
//     messagingSenderId: dotenv.env['FIREBASE_MESSAGING_SENDER_ID']!,
//     projectId: dotenv.env['FIREBASE_PROJECT_ID']!,
//     databaseURL: dotenv.env['FIREBASE_DATABASE_URL']!,
//     storageBucket: dotenv.env['FIREBASE_STORAGE_BUCKET']!,
//   );

//   static FirebaseOptions get ios => FirebaseOptions(
//     apiKey: dotenv.env['FIREBASE_API_KEY']!,
//     appId: dotenv.env['FIREBASE_APP_ID_IOS']!,
//     messagingSenderId: dotenv.env['FIREBASE_MESSAGING_SENDER_ID']!,
//     projectId: dotenv.env['FIREBASE_PROJECT_ID']!,
//     databaseURL: dotenv.env['FIREBASE_DATABASE_URL']!,
//     storageBucket: dotenv.env['FIREBASE_STORAGE_BUCKET']!,
//     iosClientId: dotenv.env['FIREBASE_IOS_CLIENT_ID']!,
//     iosBundleId: dotenv.env['FIREBASE_IOS_BUNDLE_ID']!,
//   );

//   static FirebaseOptions get macos => ios; // Assuming macOS uses the same as iOS
  
//   static FirebaseOptions get windows => FirebaseOptions(
//     apiKey: dotenv.env['FIREBASE_API_KEY']!,
//     appId: dotenv.env['FIREBASE_APP_ID_WINDOWS']!,
//     messagingSenderId: dotenv.env['FIREBASE_MESSAGING_SENDER_ID']!,
//     projectId: dotenv.env['FIREBASE_PROJECT_ID']!,
//     authDomain: dotenv.env['FIREBASE_AUTH_DOMAIN']!,
//     databaseURL: dotenv.env['FIREBASE_DATABASE_URL']!,
//     storageBucket: dotenv.env['FIREBASE_STORAGE_BUCKET']!,
//   );
// }
